#!/data/data/com.termux/files/usr/bin/bash

pkg="$(grep -R 'namespace' app/build.gradle* | head -n 1 | sed -E 's/.*namespace[[:space:]]*=?[[:space:]]*["'\'']([^"\'']+)["'\''].*/\1/')"

gradle assembleDebug --info && cp app/build/outputs/apk/debug/app-debug.apk /sdcard/Download/build_debug_${pkg}.apk
