#!/data/data/com.termux/files/usr/bin/bash

pkg="$(grep -R 'namespace' app/build.gradle* | head -n 1 | sed -E 's/.*namespace[[:space:]]*=?[[:space:]]*["'\'']([^"\'']+)["'\''].*/\1/')"

gradle assembleRelease && cp app/build/outputs/apk/release/app-release.apk /sdcard/Download/build_release_${pkg}.apk
