package dev.mr2.dpc.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF884B6B)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFFFD8E8)
private val onPrimaryContainerLight = Color(0xFF6C3353)
private val secondaryLight = Color(0xFF725763)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFFDD9E8)
private val onSecondaryContainerLight = Color(0xFF58404B)
private val tertiaryLight = Color(0xFF7F543A)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFFDBC8)
private val onTertiaryContainerLight = Color(0xFF643D25)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF8F8)
private val onBackgroundLight = Color(0xFF21191D)
private val surfaceLight = Color(0xFFFFF8F8)
private val onSurfaceLight = Color(0xFF21191D)
private val surfaceVariantLight = Color(0xFFF1DEE4)
private val onSurfaceVariantLight = Color(0xFF504349)
private val outlineLight = Color(0xFF827379)
private val outlineVariantLight = Color(0xFFD4C2C8)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF372E32)
private val inverseOnSurfaceLight = Color(0xFFFCEDF1)
private val inversePrimaryLight = Color(0xFFFCB0D5)
private val surfaceDimLight = Color(0xFFE5D6DB)
private val surfaceBrightLight = Color(0xFFFFF8F8)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFFF0F4)
private val surfaceContainerLight = Color(0xFFF9EAEE)
private val surfaceContainerHighLight = Color(0xFFF3E4E9)
private val surfaceContainerHighestLight = Color(0xFFEEDFE3)

private val primaryDark = Color(0xFFFCB0D5)
private val onPrimaryDark = Color(0xFF521D3C)
private val primaryContainerDark = Color(0xFF6C3353)
private val onPrimaryContainerDark = Color(0xFFFFD8E8)
private val secondaryDark = Color(0xFFDFBDCC)
private val onSecondaryDark = Color(0xFF402A35)
private val secondaryContainerDark = Color(0xFF58404B)
private val onSecondaryContainerDark = Color(0xFFFDD9E8)
private val tertiaryDark = Color(0xFFF3BB9A)
private val onTertiaryDark = Color(0xFF4A2811)
private val tertiaryContainerDark = Color(0xFF643D25)
private val onTertiaryContainerDark = Color(0xFFFFDBC8)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF181115)
private val onBackgroundDark = Color(0xFFEEDFE3)
private val surfaceDark = Color(0xFF181115)
private val onSurfaceDark = Color(0xFFEEDFE3)
private val surfaceVariantDark = Color(0xFF504349)
private val onSurfaceVariantDark = Color(0xFFD4C2C8)
private val outlineDark = Color(0xFF9C8D92)
private val outlineVariantDark = Color(0xFF504349)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFEEDFE3)
private val inverseOnSurfaceDark = Color(0xFF372E32)
private val inversePrimaryDark = Color(0xFF884B6B)
private val surfaceDimDark = Color(0xFF181115)
private val surfaceBrightDark = Color(0xFF40373A)
private val surfaceContainerLowestDark = Color(0xFF130C0F)
private val surfaceContainerLowDark = Color(0xFF21191D)
private val surfaceContainerDark = Color(0xFF251D21)
private val surfaceContainerHighDark = Color(0xFF30282B)
private val surfaceContainerHighestDark = Color(0xFF3B3236)

val pinkLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val pinkDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
