package dev.mr2.dpc.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF8F4A4C)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFFFDAD9)
private val onPrimaryContainerLight = Color(0xFF733336)
private val secondaryLight = Color(0xFF775656)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFFFDAD9)
private val onSecondaryContainerLight = Color(0xFF5D3F3F)
private val tertiaryLight = Color(0xFF755A2F)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFFDDB0)
private val onTertiaryContainerLight = Color(0xFF5B421A)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF8F7)
private val onBackgroundLight = Color(0xFF221919)
private val surfaceLight = Color(0xFFFFF8F7)
private val onSurfaceLight = Color(0xFF221919)
private val surfaceVariantLight = Color(0xFFF4DDDD)
private val onSurfaceVariantLight = Color(0xFF524343)
private val outlineLight = Color(0xFF857373)
private val outlineVariantLight = Color(0xFFD7C1C1)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF382E2E)
private val inverseOnSurfaceLight = Color(0xFFFFEDEC)
private val inversePrimaryLight = Color(0xFFFFB3B4)
private val surfaceDimLight = Color(0xFFE8D6D5)
private val surfaceBrightLight = Color(0xFFFFF8F7)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFFF0F0)
private val surfaceContainerLight = Color(0xFFFCEAE9)
private val surfaceContainerHighLight = Color(0xFFF6E4E3)
private val surfaceContainerHighestLight = Color(0xFFF0DEDE)

private val primaryDark = Color(0xFFFFB3B4)
private val onPrimaryDark = Color(0xFF561D21)
private val primaryContainerDark = Color(0xFF733336)
private val onPrimaryContainerDark = Color(0xFFFFDAD9)
private val secondaryDark = Color(0xFFE6BDBC)
private val onSecondaryDark = Color(0xFF44292A)
private val secondaryContainerDark = Color(0xFF5D3F3F)
private val onSecondaryContainerDark = Color(0xFFFFDAD9)
private val tertiaryDark = Color(0xFFE5C18D)
private val onTertiaryDark = Color(0xFF422C05)
private val tertiaryContainerDark = Color(0xFF5B421A)
private val onTertiaryContainerDark = Color(0xFFFFDDB0)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF1A1111)
private val onBackgroundDark = Color(0xFFF0DEDE)
private val surfaceDark = Color(0xFF1A1111)
private val onSurfaceDark = Color(0xFFF0DEDE)
private val surfaceVariantDark = Color(0xFF524343)
private val onSurfaceVariantDark = Color(0xFFD7C1C1)
private val outlineDark = Color(0xFFA08C8C)
private val outlineVariantDark = Color(0xFF524343)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFF0DEDE)
private val inverseOnSurfaceDark = Color(0xFF382E2E)
private val inversePrimaryDark = Color(0xFF8F4A4C)
private val surfaceDimDark = Color(0xFF1A1111)
private val surfaceBrightDark = Color(0xFF413736)
private val surfaceContainerLowestDark = Color(0xFF140C0C)
private val surfaceContainerLowDark = Color(0xFF221919)
private val surfaceContainerDark = Color(0xFF271D1D)
private val surfaceContainerHighDark = Color(0xFF322827)
private val surfaceContainerHighestDark = Color(0xFF3D3232)

val redLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val redDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
